name: 🐞 Bug Report
description: File a bug report to help us improve
title: ''
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please provide the following details to help us fix the issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Provide steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: checkboxes
    id: device-info
    attributes:
      label: Device Information
      description: |
        Select the type of device where you encountered the issue. Fill in the corresponding section below.
      options:
        - label: Desktop
          required: false
        - label: Smartphone
          required: false
  - type: textarea
    id: desktop-info
    attributes:
      label: Desktop Information
      description: |
        Provide as much information as you can. If you're not sure about some details, feel free to leave them out.
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
    validations:
      required: false
  - type: textarea
    id: smartphone-info
    attributes:
      label: Smartphone Information
      description: |
        Provide as much information as you can. If you're not sure about some details, feel free to leave them out.
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
