name: ✨ Feature Request
description: Suggest an idea to improve this project
title: ''
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please provide the following details to help us understand your request.
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe. (Optional)
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered (Optional)
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (Optional)
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
